name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYzY4ZjY1ZTQtOWViYi00NTJkLTg4MjctMTcyZTUwNTUyNjA3IiwidGVuYW50X2lkIjoiYmZhMGRlM2IwNmFmZGQxNjJlMmI0MmNhYjZhNTgzNmQyOGY0NDMzNDZhNmUxOWVkNDE1ZjBiMTEyNzM1ZGNiNiIsImludGVybmFsX3NlY3JldCI6ImMyNzcyMjY0LWRiN2YtNDk4NS1hM2ZiLWUzNTY1OGVjZDk3NiJ9.kdRjW5gK5fG_9v-oVFVqyRM_WOJwlXC0MeE3ocXlIlc"
JWT_SECRET="rakshit21"